# Generated by Django 5.0.7 on 2024-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_autos_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='anio',
            field=models.CharField(default='Solo poner el año: Ejemplo: 2013', max_length=5),
        ),
        migrations.AlterField(
            model_name='autos',
            name='cilindrada',
            field=models.CharField(default='Ejemplo: 2.0', max_length=5),
        ),
        migrations.AlterField(
            model_name='autos',
            name='combustible',
            field=models.CharField(default='Ejemplo: Bencinero/Diesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='autos',
            name='descripcion',
            field=models.CharField(default='Descripcion breve del vehiculo!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='autos',
            name='kilometraje',
            field=models.CharField(default='Ejemplo: 144.000', max_length=20),
        ),
        migrations.AlterField(
            model_name='autos',
            name='marca',
            field=models.CharField(default='Primera letra en Mayusculas', max_length=50),
        ),
        migrations.AlterField(
            model_name='autos',
            name='modelo',
            field=models.CharField(default='Primera letra en Mayusculas', max_length=50),
        ),
        migrations.AlterField(
            model_name='autos',
            name='precio',
            field=models.CharField(default='Ejemplo: 234.000 ', max_length=20),
        ),
        migrations.AlterField(
            model_name='autos',
            name='transmision',
            field=models.CharField(default='Ejemplo: Manual, Automatico', max_length=20),
        ),
    ]
