# Generated by Django 5.0.7 on 2024-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autos_anio_alter_autos_cilindrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='combustible',
            field=models.CharField(choices=[('Bencinero', 'Bencinero'), ('Diesel', 'Diesel')], default='Bencinero', max_length=20),
        ),
        migrations.AlterField(
            model_name='autos',
            name='precio',
            field=models.CharField(default='Ejemplo: 234.000', max_length=20),
        ),
        migrations.AlterField(
            model_name='autos',
            name='transmision',
            field=models.CharField(choices=[('Automático', 'Automático'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
    ]
