# Generated by Django 5.0.7 on 2024-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autos_combustible_alter_autos_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='recien_llegado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autos',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
